name: Java CI

on:
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compilación
      run: mvn compiler:compile -P dev
    - name: Compilación de Pruebas
      run: mvn compiler:testCompile -P dev
    - name: Pruebas de seguridad
      run: mvn surefire:test -P dev
